<?php
/**
 * Admin assets handler.
 *
 * @package Videopack
 */

namespace Videopack\Admin;

/**
 * Class Assets
 *
 * Handles admin-side script and style registration and enqueuing.
 *
 * This class manages the enqueuing of CSS and JavaScript assets required
 * for the plugin's administrative interfaces, including settings pages,
 * the encoding queue, and various UI components.
 *
 * @since      5.0.0
 * @package    Videopack
 * @subpackage Videopack/Admin
 * @author     Kyle Gilman <kylegilman@gmail.com>
 */
class Assets {
	/**
	 * Plugin options.
	 *
	 * @var array $options
	 */
	protected $options;

	/**
	 * Constructor.
	 *
	 * @param array $options Plugin options.
	 */
	public function __construct( array $options ) {

		$this->options = $options;
	}

	/**
	 * Enqueues videopack scripts and localizes data.
	 */
	public function enqueue_videopack_scripts() {
		// Loads plugin-related scripts in the admin area.

		if ( ! wp_script_is( 'videopack_admin', 'enqueued' ) ) {

			// Localize the admin script with necessary data and translated strings.
			wp_localize_script(
				'videopack_admin',
				'videopack_admin_L10n',
				array(
					'ajax_nonce'           => (string) wp_create_nonce( 'kgvid_admin_nonce' ),
					'ffmpeg_exists'        => (bool) ( $this->options['ffmpeg_exists'] ?? false ),
					'wait'                 => (string) esc_html_x( 'Wait', 'please wait', 'video-embed-thumbnail-generator' ),
					'hidevideo'            => (string) esc_html__( 'Hide video...', 'video-embed-thumbnail-generator' ),
					'choosefromvideo'      => (string) esc_html__( 'Choose from video...', 'video-embed-thumbnail-generator' ),
					'cantloadvideo'        => (string) esc_html__( "Can't load video", 'video-embed-thumbnail-generator' ),
					/* translators: %s is the path to FFmpeg. */
					'cantmakethumbs'       => (string) sprintf( esc_html__( 'Error: unable to load video in browser for thumbnail generation and FFmpeg not found at %s', 'video-embed-thumbnail-generator' ), esc_html( (string) ( $this->options['app_path'] ?? '' ) ) ),
					'choosethumbnail'      => (string) esc_html__( 'Choose Thumbnail:', 'video-embed-thumbnail-generator' ),
					'saveallthumbnails'    => (string) esc_html__( 'Save All Thumbnails', 'video-embed-thumbnail-generator' ),
					'saving'               => (string) esc_html__( 'Saving...', 'video-embed-thumbnail-generator' ),
					'loading'              => (string) esc_html__( 'Loading...', 'video-embed-thumbnail-generator' ),
					'generate'             => (string) esc_html__( 'Generate', 'video-embed-thumbnail-generator' ),
					'randomize'            => (string) esc_html__( 'Randomize', 'video-embed-thumbnail-generator' ),
					'ffmpegnotfound'       => (string) esc_html__( 'FFmpeg not found', 'video-embed-thumbnail-generator' ),
					'pleasevalidurl'       => (string) esc_html__( 'Please enter a valid video URL', 'video-embed-thumbnail-generator' ),
					'deletemessage'        => (string) esc_html__( "You are about to permanently delete the encoded video.\n 'Cancel' to stop, 'OK' to delete.", 'video-embed-thumbnail-generator' ),
					'saved'                => (string) esc_html__( 'Saved.', 'video-embed-thumbnail-generator' ),
					'runningtest'          => (string) esc_html__( 'Running test...', 'video-embed-thumbnail-generator' ),
					'ffmpegrequired'       => (string) esc_html__( 'FFmpeg required for these functions.', 'video-embed-thumbnail-generator' ),
					'featuredwarning'      => (string) esc_html__( "You are about to set all existing video thumbnails previously generated by this plugin as the featured images for their posts. There is no 'undo' button, so proceed at your own risk.", 'video-embed-thumbnail-generator' ),
					'autothumbnailwarning' => (string) esc_html__( "You are about to create thumbnails for every video in your Media Library that doesn't already have one. This might take a long time. There is no 'undo' button, so proceed at your own risk.\n\nNumber of videos without thumbnails: ", 'video-embed-thumbnail-generator' ),
					'autoencodewarning'    => (string) esc_html__( "You are about to add every video in your Media Library to the video encode queue if it hasn't already been encoded. This might take a long time.", 'video-embed-thumbnail-generator' ),
					'nothumbstomake'       => (string) esc_html__( 'No files generated. All videos are processed already.', 'video-embed-thumbnail-generator' ),
					'cancel_ok'            => (string) esc_html__( "'Cancel' to stop, 'OK' to proceed.", 'video-embed-thumbnail-generator' ),
					'processing'           => (string) esc_html__( 'Processing...', 'video-embed-thumbnail-generator' ),
					'parentwarning_posts'  => (string) esc_html__( 'You are about to set all existing video thumbnails previously generated by this plugin as attachments of their posts rather than their associated videos. Proceed at your own risk.', 'video-embed-thumbnail-generator' ),
					'parentwarning_videos' => (string) esc_html__( 'You are about to set all existing video thumbnails previously generated by this plugin as attachments of their videos rather than their associated posts. Proceed at your own risk.', 'video-embed-thumbnail-generator' ),
					'clearqueuedwarning'   => (string) esc_html__( 'You are about to clear all videos not yet encoded.', 'video-embed-thumbnail-generator' ),
					'clearallwarning'      => (string) esc_html__( 'You are about to clear all videos currently encoding, not yet encoded, completed successfully, and completed with errors.', 'video-embed-thumbnail-generator' ),
					'complete'             => (string) esc_html__( 'Complete', 'video-embed-thumbnail-generator' ),
					'track'                => (string) esc_html__( 'Track', 'video-embed-thumbnail-generator' ),
					'tracktype'            => (string) esc_html__( 'Track type:', 'video-embed-thumbnail-generator' ),
					'subtitles'            => (string) esc_html__( 'subtitles', 'video-embed-thumbnail-generator' ),
					'captions'             => (string) esc_html__( 'captions', 'video-embed-thumbnail-generator' ),
					'chapters'             => (string) esc_html__( 'chapters', 'video-embed-thumbnail-generator' ),
					'choosetextfile'       => (string) esc_html__( 'Choose a Text File', 'video-embed-thumbnail-generator' ),
					'settracksource'       => (string) esc_html__( 'Set as track source', 'video-embed-thumbnail-generator' ),
					'choosefromlibrary'    => (string) esc_html__( 'Choose from Library', 'video-embed-thumbnail-generator' ),
					'languagecode'         => (string) esc_html__( 'Language code:', 'video-embed-thumbnail-generator' ),
					'label'                => (string) esc_html_x( 'Label:', 'noun', 'video-embed-thumbnail-generator' ),
					'trackdefault'         => (string) esc_html__( 'Default:', 'video-embed-thumbnail-generator' ),
					'custom'               => (string) esc_html_x( 'Custom', 'Custom format', 'video-embed-thumbnail-generator' ),
					'clearingcache'        => (string) esc_html__( 'Clearing URL cache...', 'video-embed-thumbnail-generator' ),
					'queue_pause'          => (string) esc_html__( 'Pause the queue. Any videos currently encoding will complete.', 'video-embed-thumbnail-generator' ),
					'queue_paused'         => (string) esc_html__( 'Queue is paused. Press play button at top of screen to start.', 'video-embed-thumbnail-generator' ),
					'queue_play'           => (string) esc_html__( 'Start encoding', 'video-embed-thumbnail-generator' ),
					'nothing_to_encode'    => (string) esc_html__( 'Nothing to encode', 'video-embed-thumbnail-generator' ),
					'close'                => (string) esc_html__( 'Close', 'video-embed-thumbnail-generator' ),
					'canceling'            => (string) esc_html__( 'Canceling', 'video-embed-thumbnail-generator' ),
					'canceled'             => (string) esc_html__( 'Canceled', 'video-embed-thumbnail-generator' ),
					'elapsed'              => (string) esc_html__( 'Elapsed:', 'video-embed-thumbnail-generator' ),
					'remaining'            => (string) esc_html__( 'Remaining:', 'video-embed-thumbnail-generator' ),
					'fps'                  => (string) esc_html_x( 'FPS:', 'Frames per second', 'video-embed-thumbnail-generator' ),
					'encoding_complete'    => (string) esc_html__( 'Encoding Complete', 'video-embed-thumbnail-generator' ),
					'encoding'             => (string) esc_html__( 'Encoding', 'video-embed-thumbnail-generator' ),
					'deleted'              => (string) esc_html__( 'Deleted', 'video-embed-thumbnail-generator' ),
					'not_deleted'          => (string) esc_html__( 'Unable to delete file', 'video-embed-thumbnail-generator' ),
					'not_saved'            => (string) esc_html__( 'Error: No settings saved.', 'video-embed-thumbnail-generator' ),
				)
			);
		} // End if.
	}

	/**
	 * Conditionally enqueues scripts based on the admin hook suffix.
	 *
	 * @param string $hook_suffix The current admin page hook suffix.
	 */
	public function maybe_enqueue_videopack_scripts( $hook_suffix ) {

		if ( 'settings_page_video_embed_thumbnail_generator_settings' === $hook_suffix
			|| 'tools_page_videopack_encoding_queue' === $hook_suffix
			|| 'settings_page_videopack_network_encoding_queue' === $hook_suffix
		) {
			$this->enqueue_videopack_scripts();
		}

		if ( 'settings_page_video_embed_thumbnail_generator_settings' === $hook_suffix ) {
			wp_enqueue_style(
				'video-js',
				(string) plugins_url( '', dirname( __DIR__ ) ) . '/video-js/video-js.min.css',
				'',
				(string) VIDEOPACK_VIDEOJS_VERSION
			);
			$js_skins = array(
				'vjs-theme-videopack',
				'kg-video-js-skin',
				'vjs-theme-city',
				'vjs-theme-fantasy',
				'vjs-theme-forest',
				'vjs-theme-sea',
			);
			foreach ( $js_skins as $skin ) {
				wp_enqueue_style( (string) $skin, (string) plugins_url( '', dirname( __DIR__ ) ) . '/video-js/skins/' . $skin . '.css', '', (string) VIDEOPACK_VERSION );
			}
		}
	}
}
